# Generated by Django 5.2.9 on 2026-01-11 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_riesgo", "0009_balance_deriv_snapshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="TickDerivSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("precio", models.FloatField()),
                ("epoch", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-epoch"],
            },
        ),
        migrations.RenameIndex(
            model_name="balancederivsnapshot",
            new_name="gestion_rie_cuenta__e3f377_idx",
            old_name="gestion_rie_cuenta__6f6a9f_idx",
        ),
        migrations.RenameIndex(
            model_name="balancederivsnapshot",
            new_name="gestion_rie_created_c412ec_idx",
            old_name="gestion_rie_created_7d1f9a_idx",
        ),
        migrations.RenameIndex(
            model_name="operacion",
            new_name="gestion_rie_simbolo_573e05_idx",
            old_name="gestion_rie_simbolo_5d0c29_idx",
        ),
        migrations.RenameIndex(
            model_name="operacion",
            new_name="gestion_rie_estado_575fa3_idx",
            old_name="gestion_rie_estado_ee4a34_idx",
        ),
        migrations.RenameIndex(
            model_name="operacionderiv",
            new_name="gestion_rie_simbolo_658a8e_idx",
            old_name="gestion_rie_simbolo_f86a5c_idx",
        ),
        migrations.RenameIndex(
            model_name="operacionderiv",
            new_name="gestion_rie_estado_75c35c_idx",
            old_name="gestion_rie_estado_6c0a7a_idx",
        ),
        migrations.RenameIndex(
            model_name="operacionderiv",
            new_name="gestion_rie_updated_73cd8d_idx",
            old_name="gestion_rie_updated__2b2a8c_idx",
        ),
        migrations.AddField(
            model_name="tickderivsnapshot",
            name="cuenta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tick_snapshots",
                to="gestion_riesgo.cuenta",
            ),
        ),
        migrations.AddIndex(
            model_name="tickderivsnapshot",
            index=models.Index(
                fields=["cuenta", "-epoch"], name="gestion_rie_cuenta__c5bf90_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tickderivsnapshot",
            index=models.Index(fields=["-epoch"], name="gestion_rie_epoch_b8701c_idx"),
        ),
    ]
