# Generated by GPT on 2026-01-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_riesgo", "0010_tickderivsnapshot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="operacionderiv",
            name="entry_spot",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="operacionderiv",
            name="exit_spot",
            field=models.FloatField(blank=True, null=True),
        ),
    ]

