# Generated by Cursor on 2026-01-27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_riesgo", "0012_cuenta_default_simbolo_r10"),
    ]

    operations = [
        migrations.AddField(
            model_name="cuenta",
            name="ticks_colector_activo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="cuenta",
            name="ticks_colector_total",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cuenta",
            name="ticks_colector_ultimo_epoch",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="TickDerivHistorico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("precio", models.FloatField()),
                ("epoch", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cuenta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticks_historicos",
                        to="gestion_riesgo.cuenta",
                    ),
                ),
            ],
            options={
                "ordering": ["-epoch"],
            },
        ),
        migrations.AddIndex(
            model_name="tickderivhistorico",
            index=models.Index(fields=["cuenta", "-epoch"], name="gestion_rie_cuenta__tch_idx"),
        ),
        migrations.AddIndex(
            model_name="tickderivhistorico",
            index=models.Index(fields=["-epoch"], name="gestion_rie_epoch_tch_idx"),
        ),
    ]

