# Generated by Django 5.2.9 on 2026-03-17 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_riesgo", "0013_tick_colector_y_historico"),
    ]

    operations = [
        migrations.CreateModel(
            name="TickEURUSD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("precio", models.FloatField()),
                ("epoch", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-epoch"],
                "indexes": [
                    models.Index(fields=["-epoch"], name="gestion_rie_epoch_f6290f_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="VelaEURUSD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timeframe", models.CharField(default="M5", max_length=8)),
                ("open", models.FloatField()),
                ("high", models.FloatField()),
                ("low", models.FloatField()),
                ("close", models.FloatField()),
                ("volume", models.FloatField(default=0)),
                ("epoch_inicio", models.BigIntegerField()),
                ("epoch_fin", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-epoch_inicio"],
                "indexes": [
                    models.Index(
                        fields=["-epoch_inicio"], name="gestion_rie_epoch_i_448e5d_idx"
                    ),
                    models.Index(
                        fields=["-epoch_fin"], name="gestion_rie_epoch_f_7e88fc_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OperacionBacktest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("direccion", models.CharField(max_length=8)),
                ("precio_entrada", models.FloatField()),
                ("precio_salida", models.FloatField()),
                (
                    "resultado",
                    models.CharField(
                        choices=[("WIN", "WIN"), ("LOSS", "LOSS")], max_length=8
                    ),
                ),
                ("pnl", models.FloatField()),
                ("senal_detalle", models.JSONField(default=dict)),
                ("epoch_entrada", models.BigIntegerField()),
                ("epoch_salida", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vela_entrada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backtest_ops",
                        to="gestion_riesgo.velaeurusd",
                    ),
                ),
            ],
            options={
                "ordering": ["-epoch_entrada"],
            },
        ),
    ]
