# Generated by Django 5.2.9 on 2026-03-22 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_riesgo", "0014_tickeurusd_velaeurusd_operacionbacktest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Inversionista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(default="", max_length=100)),
                ("telefono", models.CharField(blank=True, default="", max_length=20)),
                ("whatsapp", models.CharField(blank=True, default="", max_length=20)),
                ("capital_inicial", models.FloatField(default=0.0)),
                ("capital_actual", models.FloatField(default=0.0)),
                ("ganancia_acumulada", models.FloatField(default=0.0)),
                ("ganancia_diaria", models.FloatField(default=0.0)),
                (
                    "deriv_app_id",
                    models.CharField(blank=True, default="1089", max_length=32),
                ),
                (
                    "deriv_api_token",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "deriv_account_id",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("rendimiento_diario_pct", models.FloatField(default=0.5)),
                ("fee_performance_pct", models.FloatField(default=25.0)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ACTIVO", "Activo"),
                            ("PAUSADO", "Pausado"),
                            ("RETIRADO", "Retirado"),
                        ],
                        default="ACTIVO",
                        max_length=16,
                    ),
                ),
                ("observaciones", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inversionista",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BalanceInversionista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("capital", models.FloatField()),
                ("ganancia_acumulada", models.FloatField(default=0.0)),
                ("ganancia_diaria", models.FloatField(default=0.0)),
                ("rendimiento_dia_pct", models.FloatField(default=0.0)),
                ("epoch", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "inversionista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balance_history",
                        to="gestion_riesgo.inversionista",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Liquidacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("COBRO_FEE", "Cobro de fee"),
                            ("PAGO_INVERSIONISTA", "Pago a inversionista"),
                            ("DEPOSITO", "Depósito"),
                            ("RETIRO", "Retiro de capital"),
                        ],
                        max_length=24,
                    ),
                ),
                ("ganancia_bruta", models.FloatField(default=0.0)),
                ("fee_pct", models.FloatField(default=25.0)),
                ("monto", models.FloatField(default=0.0)),
                ("observaciones", models.TextField(blank=True, default="")),
                ("fecha", models.DateField()),
                ("confirmado", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "inversionista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liquidaciones",
                        to="gestion_riesgo.inversionista",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="RendimientoDiario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("capital_inicio_dia", models.FloatField(default=0.0)),
                ("capital_fin_dia", models.FloatField(default=0.0)),
                ("ganancia_dia", models.FloatField(default=0.0)),
                ("rendimiento_pct", models.FloatField(default=0.0)),
                ("balance_deriv", models.FloatField(blank=True, null=True)),
                ("trades_count", models.IntegerField(default=0)),
                ("trades_wins", models.IntegerField(default=0)),
                ("trades_losses", models.IntegerField(default=0)),
                ("winrate", models.FloatField(default=0.0)),
                ("observaciones", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "inversionista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rendimientos_diarios",
                        to="gestion_riesgo.inversionista",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="inversionista",
            index=models.Index(fields=["user"], name="gestion_rie_user_id_bb3e01_idx"),
        ),
        migrations.AddIndex(
            model_name="inversionista",
            index=models.Index(fields=["estado"], name="gestion_rie_estado_230130_idx"),
        ),
        migrations.AddIndex(
            model_name="inversionista",
            index=models.Index(
                fields=["-created_at"], name="gestion_rie_created_121ee4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="balanceinversionista",
            index=models.Index(
                fields=["inversionista", "-fecha"],
                name="gestion_rie_inversi_609582_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="balanceinversionista",
            unique_together={("inversionista", "fecha")},
        ),
        migrations.AddIndex(
            model_name="liquidacion",
            index=models.Index(
                fields=["inversionista", "-fecha"],
                name="gestion_rie_inversi_1629d4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rendimientodiario",
            index=models.Index(
                fields=["inversionista", "-fecha"],
                name="gestion_rie_inversi_0d304e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rendimientodiario",
            index=models.Index(fields=["-fecha"], name="gestion_rie_fecha_08269e_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="rendimientodiario",
            unique_together={("inversionista", "fecha")},
        ),
    ]
