# Generated by Django 5.2.9 on 2026-03-22 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_riesgo", "0016_kyc_and_investor_flow"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GrupoAcceso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=80, unique=True)),
                ("descripcion", models.TextField(blank=True, default="")),
                (
                    "urls_permitidas",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Lista de rutas separadas por coma. Ej: /portal/,/portal/depositar/",
                    ),
                ),
                ("fecha_creado", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Grupo de Acceso",
                "verbose_name_plural": "Grupos de Acceso",
                "ordering": ["nombre"],
            },
        ),
        migrations.AlterModelOptions(
            name="deposito",
            options={"ordering": ["-fecha_creado"]},
        ),
        migrations.AlterModelOptions(
            name="rendimientofondo",
            options={"ordering": ["-anno", "-mes"]},
        ),
        migrations.AlterModelOptions(
            name="retiro",
            options={"ordering": ["-fecha_solicitud"]},
        ),
        migrations.RenameIndex(
            model_name="deposito",
            new_name="gestion_rie_inversi_19194b_idx",
            old_name="deposito_inv_fecha_idx",
        ),
        migrations.RenameIndex(
            model_name="deposito",
            new_name="gestion_rie_referen_e9afad_idx",
            old_name="deposito_ref_idx",
        ),
        migrations.RenameIndex(
            model_name="deposito",
            new_name="gestion_rie_estado_f0d9f4_idx",
            old_name="deposito_estado_idx",
        ),
        migrations.RenameIndex(
            model_name="rendimientofondo",
            new_name="gestion_rie_anno_84e8ab_idx",
            old_name="rendf_anno_mes_idx",
        ),
        migrations.RenameIndex(
            model_name="retiro",
            new_name="gestion_rie_inversi_57a24e_idx",
            old_name="retiro_inv_fecha_idx",
        ),
        migrations.RenameIndex(
            model_name="retiro",
            new_name="gestion_rie_estado_143ac0_idx",
            old_name="retiro_estado_idx",
        ),
        migrations.AlterField(
            model_name="deposito",
            name="estado",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente"),
                    ("CONFIRMADO", "Confirmado"),
                    ("RECHAZADO", "Rechazado"),
                    ("CANCELADO", "Cancelado"),
                ],
                default="PENDIENTE",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="deposito",
            name="metodo",
            field=models.CharField(blank=True, default="BOLD", max_length=32),
        ),
        migrations.AlterField(
            model_name="deposito",
            name="monto",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="deposito",
            name="notas",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="deposito",
            name="referencia",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="inversionista",
            name="capital_objetivo",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="inversionista",
            name="como_se_entero",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AlterField(
            model_name="inversionista",
            name="documento_identidad",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="inversionista",
            name="fecha_nacimiento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="inversionista",
            name="genero",
            field=models.CharField(
                choices=[
                    ("M", "Masculino"),
                    ("F", "Femenino"),
                    ("O", "Otro"),
                    ("N", "Prefiero no decir"),
                ],
                default="N",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="inversionista",
            name="nacionalidad",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="rendimientofondo",
            name="anno",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="rendimientofondo",
            name="ganancia",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="rendimientofondo",
            name="mes",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="rendimientofondo",
            name="rendimiento_pct",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="retiro",
            name="destino",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AlterField(
            model_name="retiro",
            name="estado",
            field=models.CharField(
                choices=[
                    ("SOLICITADO", "Solicitado"),
                    ("EN_PROCESO", "En proceso"),
                    ("COMPLETADO", "Completado"),
                    ("RECHAZADO", "Rechazado"),
                ],
                default="SOLICITADO",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="retiro",
            name="monto",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="retiro",
            name="notas_admin",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="grupoacceso",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="grupos_creados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="grupoacceso",
            name="usuarios",
            field=models.ManyToManyField(
                blank=True, related_name="grupos_acceso", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
