# Generated by Django 5.2.12 on 2026-03-28 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_riesgo", "0017_grupo_acceso"),
    ]

    operations = [
        migrations.AddField(
            model_name="cuenta",
            name="bot_activo",
            field=models.BooleanField(
                default=True, help_text="Activar o desactivar el bot manualmente"
            ),
        ),
    ]
