# Generated by Django 5.2.9 on 2026-03-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_riesgo", "0018_bot_activo"),
    ]

    operations = [
        migrations.CreateModel(
            name="EstadisticasBinance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("simbolo", models.CharField(max_length=20, unique=True)),
                ("total_ops", models.IntegerField(default=0)),
                ("wins", models.IntegerField(default=0)),
                ("losses", models.IntegerField(default=0)),
                (
                    "profit_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("win_streak", models.IntegerField(default=0)),
                ("loss_streak", models.IntegerField(default=0)),
                ("max_win_streak", models.IntegerField(default=0)),
                ("max_loss_streak", models.IntegerField(default=0)),
                (
                    "balance_ficticio",
                    models.DecimalField(decimal_places=2, default=1000, max_digits=12),
                ),
                ("ultima_operacion", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Estadistica Binance",
                "verbose_name_plural": "Estadisticas Binance",
            },
        ),
        migrations.CreateModel(
            name="OperacionBinance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("simbolo", models.CharField(max_length=20)),
                (
                    "direccion",
                    models.CharField(
                        choices=[("CALL", "Call (Compra)"), ("PUT", "Put (Venta)")],
                        max_length=10,
                    ),
                ),
                (
                    "precio_entrada",
                    models.DecimalField(decimal_places=8, max_digits=20),
                ),
                ("razon", models.CharField(blank=True, default="", max_length=100)),
                (
                    "confianza",
                    models.CharField(
                        choices=[
                            ("alta", "Alta"),
                            ("media", "Media"),
                            ("baja", "Baja"),
                        ],
                        default="media",
                        max_length=10,
                    ),
                ),
                ("es_win", models.BooleanField(default=False)),
                (
                    "profit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "win_rate_momento",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "profit_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("num_operacion", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Operacion Binance",
                "verbose_name_plural": "Operaciones Binance",
                "ordering": ["-created_at"],
            },
        ),
    ]
