# Generated by Django 5.2.9 on 2026-03-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_riesgo", "0019_operaciones_binance"),
    ]

    operations = [
        migrations.CreateModel(
            name="TickBinance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("simbolo", models.CharField(db_index=True, max_length=20)),
                ("precio", models.DecimalField(decimal_places=8, max_digits=20)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Tick Binance",
                "verbose_name_plural": "Ticks Binance",
                "ordering": ["-timestamp"],
            },
        ),
    ]
