# Generated by Django 5.2.9 on 2026-03-29 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_riesgo", "0020_tick_binance"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionEstrategia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(default="binance", max_length=50)),
                (
                    "ema_gap_min",
                    models.FloatField(
                        default=0.2, help_text="Gap mínimo entre EMA21 y EMA50 (%)"
                    ),
                ),
                (
                    "adx_min",
                    models.FloatField(
                        default=20.0, help_text="ADX mínimo para tendencia"
                    ),
                ),
                ("rsi_min", models.FloatField(default=30.0, help_text="RSI mínimo")),
                ("rsi_max", models.FloatField(default=70.0, help_text="RSI máximo")),
                (
                    "bb_min",
                    models.FloatField(
                        default=0.2, help_text="Posición mínima en Bollinger Bands"
                    ),
                ),
                (
                    "bb_max",
                    models.FloatField(
                        default=0.8, help_text="Posición máxima en Bollinger Bands"
                    ),
                ),
                (
                    "cooldown_ticks",
                    models.IntegerField(
                        default=150, help_text="Ticks de espera entre operaciones"
                    ),
                ),
                (
                    "stake",
                    models.FloatField(default=1.0, help_text="Monto por operación"),
                ),
                (
                    "duracion_segundos",
                    models.IntegerField(
                        default=60, help_text="Duración de cada operación"
                    ),
                ),
                (
                    "payout",
                    models.FloatField(default=0.95, help_text="Payout esperado"),
                ),
                (
                    "activa",
                    models.BooleanField(
                        default=True, help_text="Si está activa, el bot usa esta config"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuración Estrategia",
                "verbose_name_plural": "Configuraciones Estrategia",
            },
        ),
    ]
