# Generated by Django 5.2.9 on 2026-03-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_riesgo", "0021_configuracionestrategia"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracionestrategia",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("estricta", "Estricta"),
                    ("media", "Media"),
                    ("flexible", "Flexible"),
                ],
                default="estricta",
                max_length=20,
            ),
        ),
    ]
