# Generated by Django 5.0.4 on 2025-11-09 02:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivoPermitido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('habilitado', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Activo permitido',
                'verbose_name_plural': 'Activos permitidos',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_actual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('meta_actual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('stop_loss_actual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('estado', models.CharField(choices=[('operando', 'Operando'), ('pausado', 'Pausado')], default='operando', max_length=15)),
                ('activo_seleccionado', models.CharField(blank=True, max_length=80)),
                ('perdida_acumulada', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('ganancia_acumulada', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('mejor_horario', models.TimeField(blank=True, null=True)),
                ('pausado_desde', models.DateTimeField(blank=True, null=True)),
                ('pausa_finaliza', models.DateTimeField(blank=True, null=True)),
                ('en_operacion', models.BooleanField(default=False)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del bot',
                'verbose_name_plural': 'Configuraciones del bot',
            },
        ),
    ]
