# Generated by Django 5.0.4 on 2025-11-11 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_configuracionbot_balance_meta_base_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionbot',
            name='ultima_simulacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
