# Generated by Django 5.0.4 on 2025-11-15 14:25

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_activopermitido_hora_mejor_simulacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CooldownActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(help_text='Razón del cooldown (señal contradictoria, micro-congestión, etc.)', max_length=100)),
                ('finaliza_en', models.DateTimeField(db_index=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooldowns', to='core.activopermitido')),
            ],
            options={
                'verbose_name': 'Cooldown de activo',
                'verbose_name_plural': 'Cooldowns de activos',
                'ordering': ('-finaliza_en',),
                'indexes': [models.Index(fields=['activo', 'finaliza_en'], name='trading_coo_activo__f445ed_idx')],
            },
        ),
        migrations.CreateModel(
            name='IndicadoresActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('momentum_simple', models.DecimalField(decimal_places=5, default=Decimal('0.00'), max_digits=15)),
                ('momentum_pct', models.DecimalField(decimal_places=4, default=Decimal('0.00'), help_text='Cambio porcentual entre tick inicial y final', max_digits=10)),
                ('volatilidad', models.DecimalField(decimal_places=4, default=Decimal('0.00'), help_text='Desviación estándar de los últimos ticks', max_digits=10)),
                ('tendencia_ema', models.DecimalField(decimal_places=5, default=Decimal('0.00'), help_text='EMA(10) aplicada a los últimos ticks', max_digits=15)),
                ('precio_actual', models.DecimalField(decimal_places=5, default=Decimal('0.00'), max_digits=15)),
                ('rate_of_change', models.DecimalField(decimal_places=4, default=Decimal('0.00'), help_text='Pendiente de regresión lineal', max_digits=10)),
                ('fuerza_movimiento', models.DecimalField(decimal_places=5, default=Decimal('0.00'), help_text='|EMA - precio actual|', max_digits=15)),
                ('consistencia', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de ticks consecutivos en la misma dirección', max_digits=5)),
                ('score_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Score combinado 0-100', max_digits=5)),
                ('direccion_sugerida', models.CharField(choices=[('CALL', 'CALL'), ('PUT', 'PUT'), ('NONE', 'Ninguna')], default='NONE', max_length=4)),
                ('ticks_analizados', models.IntegerField(default=0)),
                ('calculado_en', models.DateTimeField(auto_now=True, db_index=True)),
                ('activo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='core.activopermitido')),
            ],
            options={
                'verbose_name': 'Indicadores de activo',
                'verbose_name_plural': 'Indicadores de activos',
                'ordering': ('-score_total',),
                'indexes': [models.Index(fields=['-score_total'], name='trading_ind_score_t_769e87_idx'), models.Index(fields=['-calculado_en'], name='trading_ind_calcula_1d5147_idx')],
            },
        ),
        migrations.CreateModel(
            name='RendimientoActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winrate_dinamico', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Winrate de las últimas N operaciones', max_digits=5)),
                ('total_operaciones', models.IntegerField(default=0)),
                ('operaciones_ganadas', models.IntegerField(default=0)),
                ('operaciones_perdidas', models.IntegerField(default=0)),
                ('drawdown_maximo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Drawdown máximo histórico', max_digits=10)),
                ('drawdown_actual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Drawdown actual', max_digits=10)),
                ('beneficio_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('perdida_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('hora', models.TimeField(db_index=True, help_text='Franja horaria (HH:MM)')),
                ('actualizado_en', models.DateTimeField(auto_now=True, db_index=True)),
                ('periodo_desde', models.DateTimeField(blank=True, help_text='Inicio del período de análisis', null=True)),
                ('periodo_hasta', models.DateTimeField(blank=True, help_text='Fin del período de análisis', null=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendimientos', to='core.activopermitido')),
            ],
            options={
                'verbose_name': 'Rendimiento de activo',
                'verbose_name_plural': 'Rendimientos de activos',
                'ordering': ('-winrate_dinamico',),
                'indexes': [models.Index(fields=['-winrate_dinamico'], name='trading_ren_winrate_11b753_idx'), models.Index(fields=['activo', 'hora'], name='trading_ren_activo__d56ff1_idx'), models.Index(fields=['-actualizado_en'], name='trading_ren_actuali_24eab4_idx')],
                'unique_together': {('activo', 'hora')},
            },
        ),
        migrations.CreateModel(
            name='TickCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=5, max_digits=15)),
                ('epoch', models.BigIntegerField(db_index=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tick_caches', to='core.activopermitido')),
            ],
            options={
                'verbose_name': 'Tick en cache',
                'verbose_name_plural': 'Ticks en cache',
                'ordering': ('-epoch',),
                'indexes': [models.Index(fields=['-epoch', 'activo'], name='trading_tic_epoch_02711c_idx'), models.Index(fields=['activo', '-timestamp'], name='trading_tic_activo__b810c0_idx')],
            },
        ),
    ]
