# Generated by Django 5.2.9 on 2026-03-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActivoTrading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("simbolo", models.CharField(max_length=20, unique=True)),
                ("nombre", models.CharField(max_length=50)),
                (
                    "pair_type",
                    models.CharField(
                        choices=[
                            ("forex", "Forex"),
                            ("futures", "Futures"),
                            ("crypto", "Crypto"),
                        ],
                        default="forex",
                        max_length=20,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Activo Trading",
                "verbose_name_plural": "Activos Trading",
            },
        ),
        migrations.CreateModel(
            name="ConfiguracionTrading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(default="forex", max_length=50)),
                (
                    "ema_gap_min",
                    models.FloatField(
                        default=0.2, help_text="Gap mínimo entre EMA21 y EMA50 (%)"
                    ),
                ),
                (
                    "adx_min",
                    models.FloatField(
                        default=20.0, help_text="ADX mínimo para tendencia"
                    ),
                ),
                ("rsi_min", models.FloatField(default=30.0, help_text="RSI mínimo")),
                ("rsi_max", models.FloatField(default=70.0, help_text="RSI máximo")),
                (
                    "bb_min",
                    models.FloatField(
                        default=0.2, help_text="Posición mínima en Bollinger Bands"
                    ),
                ),
                (
                    "bb_max",
                    models.FloatField(
                        default=0.8, help_text="Posición máxima en Bollinger Bands"
                    ),
                ),
                ("cooldown_ticks", models.IntegerField(default=150)),
                ("stake", models.FloatField(default=1.0)),
                ("duracion_segundos", models.IntegerField(default=60)),
                ("payout", models.FloatField(default=0.95)),
                ("activa", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuración Trading",
                "verbose_name_plural": "Configuraciones Trading",
            },
        ),
        migrations.CreateModel(
            name="EstadisticasTrading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("simbolo", models.CharField(max_length=20, unique=True)),
                ("total_ops", models.IntegerField(default=0)),
                ("wins", models.IntegerField(default=0)),
                ("losses", models.IntegerField(default=0)),
                (
                    "profit_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "balance_ficticio",
                    models.DecimalField(decimal_places=2, default=1000, max_digits=20),
                ),
                ("win_streak", models.IntegerField(default=0)),
                ("loss_streak", models.IntegerField(default=0)),
                ("max_win_streak", models.IntegerField(default=0)),
                ("max_loss_streak", models.IntegerField(default=0)),
                ("ultima_operacion", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Estadísticas Trading",
                "verbose_name_plural": "Estadísticas Trading",
            },
        ),
        migrations.CreateModel(
            name="OperacionTrading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("simbolo", models.CharField(max_length=20)),
                (
                    "direccion",
                    models.CharField(
                        choices=[("CALL", "CALL"), ("PUT", "PUT")], max_length=10
                    ),
                ),
                (
                    "precio_entrada",
                    models.DecimalField(decimal_places=8, max_digits=20),
                ),
                (
                    "precio_salida",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                ("razon", models.CharField(max_length=100)),
                (
                    "confianza",
                    models.CharField(
                        choices=[
                            ("alta", "Alta"),
                            ("media", "Media"),
                            ("baja", "Baja"),
                        ],
                        default="media",
                        max_length=20,
                    ),
                ),
                ("es_win", models.BooleanField(default=False)),
                (
                    "profit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("num_operacion", models.IntegerField(default=0)),
                ("win_rate_momento", models.FloatField(default=0)),
                (
                    "profit_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Operación Trading",
                "verbose_name_plural": "Operaciones Trading",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TickTrading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("simbolo", models.CharField(db_index=True, max_length=20)),
                ("precio", models.DecimalField(decimal_places=8, max_digits=20)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Tick Trading",
                "verbose_name_plural": "Ticks Trading",
                "ordering": ["-timestamp"],
            },
        ),
    ]
