# Generated by Django 5.0.4 on 2025-11-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooldownactivo',
            name='motivo',
            field=models.CharField(help_text='Razón del cooldown (señal contradictoria, micro-congestión, etc.)', max_length=40),
        ),
    ]
