# Generated by Django 5.2.9 on 2026-03-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0002_configuraciontrading_tipo"),
    ]

    operations = [
        migrations.CreateModel(
            name="EstadisticasSymbolo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("simbolo", models.CharField(max_length=20, unique=True)),
                ("total_ticks", models.IntegerField(default=0)),
                ("total_ops", models.IntegerField(default=0)),
                ("ops_ganadas", models.IntegerField(default=0)),
                ("ops_perdidas", models.IntegerField(default=0)),
                (
                    "profit_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("ultima_actualizacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Estadísticas Símbolo",
                "verbose_name_plural": "Estadísticas Símbolos",
            },
        ),
        migrations.CreateModel(
            name="HistorialTicks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("simbolo", models.CharField(db_index=True, max_length=20)),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("open_price", models.DecimalField(decimal_places=8, max_digits=20)),
                ("high_price", models.DecimalField(decimal_places=8, max_digits=20)),
                ("low_price", models.DecimalField(decimal_places=8, max_digits=20)),
                ("close_price", models.DecimalField(decimal_places=8, max_digits=20)),
                ("tick_count", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Historial Ticks",
                "verbose_name_plural": "Historial Ticks",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddField(
            model_name="ticktrading",
            name="precio_ask",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="ticktrading",
            name="precio_bid",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="ticktrading",
            name="volumen",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="ticktrading",
            index=models.Index(
                fields=["simbolo", "-timestamp"], name="trading_tic_simbolo_da5b48_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="historialticks",
            index=models.Index(
                fields=["simbolo", "-timestamp"], name="trading_his_simbolo_aa68d8_idx"
            ),
        ),
    ]
