# Generated by Django 5.2.9 on 2026-03-31 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0003_estadisticassymbolo_historialticks_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BalanceGlobal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=1000, max_digits=20),
                ),
                (
                    "capital_inicial",
                    models.DecimalField(decimal_places=2, default=1000, max_digits=20),
                ),
                ("ultima_actualizacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Balance Global",
                "verbose_name_plural": "Balances Globales",
            },
        ),
    ]
