# Generated by Django 5.0.4 on 2025-11-09 02:38

import django.db.models.manager
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoHorarioSimulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('total_operaciones', models.PositiveIntegerField(default=0)),
                ('operaciones_ganadas', models.PositiveIntegerField(default=0)),
                ('operaciones_perdidas', models.PositiveIntegerField(default=0)),
                ('winrate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('fecha_calculo', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Resultado de simulación por horario',
                'verbose_name_plural': 'Resultados de simulación por horario',
                'ordering': ('-fecha_calculo', '-winrate'),
                'unique_together': {('hora_inicio', 'fecha_calculo')},
            },
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
    ]
