# Generated by Django 5.0.4 on 2025-11-11 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='resultadohorariosimulacion',
            managers=[
            ],
        ),
    ]
