# Generated by Django 5.2.12 on 2026-03-21 02:09

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("FREE", "Gratis"),
                            ("BASICO", "Basico"),
                            ("PRO", "Profesional"),
                            ("INSTITUCIONAL", "Institucional"),
                        ],
                        default="BASICO",
                        max_length=20,
                    ),
                ),
                ("max_cuentas_deriv", models.IntegerField(default=1)),
                ("max_symbols", models.IntegerField(default=1)),
                ("permite_backtest", models.BooleanField(default=False)),
                ("permite_api", models.BooleanField(default=False)),
                ("permite_white_label", models.BooleanField(default=False)),
                ("soporte_prioritario", models.BooleanField(default=False)),
                ("max_trades_dia", models.IntegerField(default=50)),
                ("max_ticks_por_dia", models.IntegerField(default=10000)),
                (
                    "precio_mensual",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "precio_trimestral",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "precio_anual",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("activo", models.BooleanField(default=True)),
                ("orden", models.IntegerField(default=0)),
                ("dias_trial", models.IntegerField(default=0)),
                ("descripcion", models.TextField(blank=True)),
            ],
            options={
                "db_table": "plans",
                "ordering": ["orden", "precio_mensual"],
            },
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("telefono", models.CharField(blank=True, max_length=20)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ACTIVO", "Activo"),
                            ("SUSPENDIDO", "Suspendido"),
                            ("CANCELADO", "Cancelado"),
                            ("TRIAL", "Prueba gratuita"),
                        ],
                        default="TRIAL",
                        max_length=20,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_expiracion_trial", models.DateTimeField(blank=True, null=True)),
                ("max_cuentas_deriv", models.IntegerField(default=1)),
                ("max_symbols", models.IntegerField(default=3)),
                ("permite_api", models.BooleanField(default=False)),
                ("notas", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "tenants",
                "ordering": ["-fecha_creacion"],
                "indexes": [
                    models.Index(fields=["slug"], name="tenants_slug_3181c2_idx"),
                    models.Index(fields=["email"], name="tenants_email_64287b_idx"),
                    models.Index(fields=["estado"], name="tenants_estado_a5bb45_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("SUPER_ADMIN", "Super Administrador"),
                            ("ADMIN_TENANT", "Administrador Tenant"),
                            ("OPERADOR", "Operador"),
                            ("VIEWER", "Solo lectura"),
                        ],
                        default="OPERADOR",
                        max_length=20,
                    ),
                ),
                ("puede_operar", models.BooleanField(default=True)),
                ("puede_configurar", models.BooleanField(default=False)),
                ("puede_ver_reportes", models.BooleanField(default=True)),
                ("timezone", models.CharField(default="America/Bogota", max_length=50)),
                ("tema", models.CharField(default="light", max_length=20)),
                ("last_login_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("last_login_device", models.CharField(blank=True, max_length=255)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usuarios",
                        to="subscriptions.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Suscripcion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ACTIVA", "Activa"),
                            ("CANCELADA", "Cancelada"),
                            ("EXPIRADA", "Expirada"),
                            ("TRIAL", "Prueba gratuita"),
                            ("PENDIENTE", "Pendiente de pago"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                (
                    "periodicidad",
                    models.CharField(
                        choices=[
                            ("MENSUAL", "Mensual"),
                            ("TRIMESTRAL", "Trimestral"),
                            ("ANUAL", "Anual"),
                        ],
                        default="MENSUAL",
                        max_length=20,
                    ),
                ),
                ("fecha_inicio", models.DateTimeField(blank=True, null=True)),
                ("fecha_expiracion", models.DateTimeField(blank=True, null=True)),
                ("fecha_cancelacion", models.DateTimeField(blank=True, null=True)),
                (
                    "stripe_subscription_id",
                    models.CharField(blank=True, max_length=100),
                ),
                ("stripe_customer_id", models.CharField(blank=True, max_length=100)),
                ("notas", models.TextField(blank=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="suscripciones",
                        to="subscriptions.plan",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suscripciones",
                        to="subscriptions.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "subscriptions",
                "ordering": ["-fecha_inicio"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "estado"],
                        name="subscriptio_tenant__9d361c_idx",
                    ),
                    models.Index(
                        fields=["fecha_expiracion"],
                        name="subscriptio_fecha_e_58c19b_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LogAuditoria",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "accion",
                    models.CharField(
                        choices=[
                            ("LOGIN", "Inicio de sesion"),
                            ("LOGOUT", "Cierre de sesion"),
                            ("LOGIN_FAILED", "Login fallido"),
                            ("CREAR", "Crear registro"),
                            ("ACTUALIZAR", "Actualizar registro"),
                            ("ELIMINAR", "Eliminar registro"),
                            ("TRADING", "Operacion de trading"),
                            ("CAMBIO_PLAN", "Cambio de plan"),
                            ("ERROR", "Error del sistema"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descripcion", models.CharField(max_length=500)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("datos_extra", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs_auditoria",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs_auditoria",
                        to="subscriptions.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["usuario", "-timestamp"],
                        name="audit_logs_usuario_5354f3_idx",
                    ),
                    models.Index(
                        fields=["tenant", "-timestamp"],
                        name="audit_logs_tenant__79c676_idx",
                    ),
                    models.Index(
                        fields=["accion", "-timestamp"],
                        name="audit_logs_accion_0d699a_idx",
                    ),
                ],
            },
        ),
    ]
