# Generated by Django 5.0.4 on 2025-11-09 02:38

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.CharField(max_length=80)),
                ('direccion', models.CharField(choices=[('CALL', 'CALL'), ('PUT', 'PUT')], max_length=4)),
                ('precio_entrada', models.DecimalField(decimal_places=5, max_digits=12)),
                ('precio_cierre', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('monto_invertido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('confianza', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Porcentaje de confianza')),
                ('resultado', models.CharField(choices=[('win', 'Ganada'), ('loss', 'Perdida'), ('pending', 'Pendiente')], default='pending', max_length=10)),
                ('numero_contrato', models.CharField(max_length=40, unique=True)),
                ('hora_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('hora_fin', models.DateTimeField(blank=True, null=True)),
                ('beneficio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('es_simulada', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Operación',
                'verbose_name_plural': 'Operaciones',
                'ordering': ('-hora_inicio',),
            },
        ),
    ]
