# Generated by Django 5.0.4 on 2025-11-09 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.CharField(max_length=80)),
                ('epoch', models.DateTimeField()),
                ('precio', models.DecimalField(decimal_places=5, max_digits=12)),
                ('pip_size', models.PositiveIntegerField(default=0)),
                ('datos', models.JSONField(blank=True, default=dict)),
                ('recibido', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-epoch',),
                'indexes': [models.Index(fields=['activo', 'epoch'], name='historial_t_activo_500c8f_idx')],
                'unique_together': {('activo', 'epoch')},
            },
        ),
    ]
