# Generated by Django 5.0.4 on 2025-11-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0002_tick'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_esperado', models.DecimalField(decimal_places=2, help_text='Balance calculado desde operaciones registradas', max_digits=12)),
                ('balance_real', models.DecimalField(decimal_places=2, help_text='Balance obtenido de la API de Deriv', max_digits=12)),
                ('diferencia', models.DecimalField(decimal_places=2, help_text='Diferencia entre balance real y esperado (real - esperado)', max_digits=12)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la discrepancia detectada')),
                ('detectado_en', models.DateTimeField(auto_now_add=True)),
                ('balance_anterior', models.DecimalField(blank=True, decimal_places=2, help_text='Balance anterior antes de la sincronización', max_digits=12, null=True)),
            ],
            options={
                'verbose_name': 'Ajuste de balance',
                'verbose_name_plural': 'Ajustes de balance',
                'ordering': ('-detectado_en',),
                'indexes': [models.Index(fields=['-detectado_en'], name='historial_a_detecta_4d10e8_idx')],
            },
        ),
    ]
